package com.phasico.infinistack.mixins.opencomputers;

import li.cil.oc.common.entity.Drone;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Pseudo;
import com.phasico.infinistack.helper.Configurables;

@Mixin(Drone.class)
@Pseudo
public abstract class MixinDrone {

    //TODO: Find a way to mixin into the anonymous classes generated by scala

    /*@Overwrite(remap = false)
    public int func_70297_j_() {
        return Configurables.maxStackSize;
    }*/

}
